-- AlterTable
ALTER TABLE "AllUKPlan" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "AllUSPlan" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "UserAllUKPlan" ALTER COLUMN "Paidprice" SET DEFAULT 0,
ALTER COLUMN "Paidprice" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "UserAllUSPlan" ALTER COLUMN "Paidprice" SET DEFAULT 0,
ALTER COLUMN "Paidprice" SET DATA TYPE DOUBLE PRECISION;
